name: Deploy via SSH

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: "true"
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      - name: Install npm dependencies
        run: npm install
      - name: Run build task
        run: npm run export --if-present
      - name: Deploy to Server (out/)
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --chown=www-data:www-data --delete"
          SOURCE: "out/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/out/, /node_modules/"
